### ISSUE TITLE
Choix des images du slider

### ISSUE THREAD

**Issue by jmlabesse** [jmlabesse/Project_Geotlandes#1]
- [x] Sélection des photos pour intégration dans le slider
- [x] Redimensionnement des photos si nécessaire

**Comment by jmlabesse** [comment]
J'ai choisi les images suivantes :

**Comment by jmlabesse** [comment]
J'ai choisi les images suivantes :
9-2015 2.jpg
90-2014 1.jpg
p1010575.jpg
p1010589.jpg
p1010613.jpg

**Comment by jmlabesse** [comment]
J'ai choisi les images suivantes : 
- 9-2015 2.jpg
- 90-2014 1.jpg
- p1010575.jpg
- p1010589.jpg
- p1010613.jpg

**Comment by SHINOATV** [comment]
Le slider n'est-il pas censé faire 3 à 4 images maximum ?

**Comment by SHINOATV** [comment]
Je valide les images SAUF la 90-2014 1.jpg puisque l'image est en mode portrait donc non adapté pour un slider horizontal.

**Comment by jmlabesse** [comment]
Ok, je vais garder les 3 qui sont déjà bien proportionnées + la "90-2014 2.jpg" que je vais redimensionné.
