### ISSUE TITLE
Barre de footer

### ISSUE THREAD

**Issue by jmlabesse** [jmlabesse/Project_Geotlandes#11]
Créer barre de footer.
Les liens vers les profils réseaux sociaux sont les suivantes :
→ Facebook : https://fr-fr.facebook.com/pages/sarl-Geotlandes/423538047850646
→ LinkedIn : https://www.linkedin.com/in/cecile-bibette-5382a6ba/

**Comment by SHINOATV** [comment]
Est-tu sur que ce sont les bon liens ? La page Facebook compte 0 "J'aime" et celle LinkedLn ne comporte pas de photo ni d'informations détaillés ce qui ne fait pas très professionnel.

**Comment by jmlabesse** [comment]
C'est les seuls qui correspondent. Je renverrai un message au formateur pour qu'il confirme les liens.

- [x] Liens Confirmés
- [ ] En Attente de Confirmation
- [ ] Liens Non Confirmés

**Comment by SHINOATV** [comment]
J'ai tout cassé, il faut que je revoye le code du footer
