### ISSUE TITLE
Menu de navigation responsif

### ISSUE THREAD

**Issue by SHINOATV** [jmlabesse/Project_Geotlandes#16]

**Comment by SHINOATV** [comment]
Il manque la modale pour le moment

**Comment by SHINOATV** [comment]
Il me faudrait l'icone "accueil" , on en prend une sur internet ou en fait une nous-même ?

**Comment by philippedebridiers** [comment]
Sur [bootstrap](http://getbootstrap.com/components/) il y a des glyphicon et notamment celui-ci : glyphicon glyphicon-home
