### ISSUE TITLE
Choix des clients de la page “Clients” 

### ISSUE THREAD

**Issue by jmlabesse** [jmlabesse/Project_Geotlandes#4]
- [ ] Recherche des logos et descriptions

**Comment by jmlabesse** [comment]
En attente des infos du client

**Comment by SHINOATV** [comment]
Avons nous reçu la liste des clients ayant potentiellement utilisé leurs services ?
- [ ] oui
- [x] non

**Comment by jmlabesse** [comment]
J'ai demandé à Jonathan et en fait il faut qu'on les choisisse nous-mêmes (du genre Conseil Général, Ville de Pissos, ...)
