### ISSUE TITLE
Police d’écriture 

### ISSUE THREAD

**Issue by jmlabesse** [jmlabesse/Project_Geotlandes#5]
1 pour les titres, 1 pour les paragraphes

**Comment by jmlabesse** [comment]
Ça te va comme police ?

**Comment by SHINOATV** [comment]
Elle est bien, celle de la maquette l'est tout aussi

**Comment by jmlabesse** [comment]
J'avais proposé : 
- pour les titres : Roboto ;
- pour les paragraphes : Open Sans ;
