### ISSUE TITLE
Boxs de présentation page d'accueil

### ISSUE THREAD

**Issue by jmlabesse** [jmlabesse/Project_Geotlandes#9]
Créer modèle de box pour la présentation des services

**Comment by SHINOATV** [comment]
Avez vous réfléchis à un design particulier ? Arrondir les bords ? Changer la couleur ? Changer le design ?

**Comment by philippedebridiers** [comment]
Hum non pas vraiment. Je crois que l'on va voir cela demain histoire d'avoir quelque chose d'harmonisé sur toutes les pages.
